// GENERATED by scripts/fetch-triple-tiles.mjs from scripts/triple-tiles.json. Do not edit by hand.
// Pictures: Microsoft Fluent Emoji, "3D" style, 128x128 PNG, MIT license (see THIRD_PARTY_NOTICES.md).
import type { PictureCollection } from './types';

export const TRIPLE_TILES_FLUENT: PictureCollection = {
  id: 'triple-tiles-fluent',
  basePath: 'triple-tiles',
  extension: 'png',
  pictures: [
  { id: 'strawberry', name: { fr: 'Fraise', en: 'Strawberry' } },
  { id: 'cherries', name: { fr: 'Cerises', en: 'Cherries' } },
  { id: 'green-apple', name: { fr: 'Pomme verte', en: 'Green apple' } },
  { id: 'banana', name: { fr: 'Banane', en: 'Banana' } },
  { id: 'avocado', name: { fr: 'Avocat', en: 'Avocado' } },
  { id: 'blueberries', name: { fr: 'Myrtilles', en: 'Blueberries' } },
  { id: 'butterfly', name: { fr: 'Papillon', en: 'Butterfly' } },
  { id: 'blossom', name: { fr: 'Fleur', en: 'Blossom' } },
  { id: 'gem-stone', name: { fr: 'Gemme', en: 'Gem stone' } },
  { id: 'grapes', name: { fr: 'Raisin', en: 'Grapes' } },
  { id: 'lemon', name: { fr: 'Citron', en: 'Lemon' } },
  { id: 'carrot', name: { fr: 'Carotte', en: 'Carrot' } },
  { id: 'sunflower', name: { fr: 'Tournesol', en: 'Sunflower' } },
  { id: 'tulip', name: { fr: 'Tulipe', en: 'Tulip' } },
  { id: 'mushroom', name: { fr: 'Champignon', en: 'Mushroom' } },
  { id: 'peach', name: { fr: 'Pêche', en: 'Peach' } },
  { id: 'watermelon', name: { fr: 'Pastèque', en: 'Watermelon' } },
  { id: 'lady-beetle', name: { fr: 'Coccinelle', en: 'Lady beetle' } },
  ],
};
