// Fetches the Mahjong tile pictures from Microsoft's Fluent Emoji (MIT), "Color" style only,
// optimizes them and writes:
//   public/tiles/<id>.svg            the pictures (served as plain files, cached for offline by the service worker)
//   src/pictures/tilesFluent.ts      the "tiles-fluent" collection definition
// The picture list lives in scripts/tiles.json (id, Fluent folder name, FR and EN names).
// Run with:  node scripts/fetch-tiles.mjs
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { optimize } from 'svgo';

// Pinned commit of https://github.com/microsoft/fluentui-emoji so the result is reproducible.
const FLUENT_REF = '1ffb34c752ecf5d402f04cfb4b392c77f57c54bc';
const tiles = JSON.parse(readFileSync(new URL('./tiles.json', import.meta.url), 'utf8'));

const svgoConfig = {
  multipass: true,
  floatPrecision: 2,
  plugins: [
    'preset-default', // keeps the viewBox in svgo 4
    'removeDimensions', // sized by CSS; the viewBox keeps it scalable
  ],
};

mkdirSync(new URL('../public/tiles/', import.meta.url), { recursive: true });
mkdirSync(new URL('../src/pictures/', import.meta.url), { recursive: true });

let total = 0;
for (const tile of tiles) {
  const file = `${tile.source.toLowerCase().replace(/ /g, '_')}_color.svg`;
  const url = `https://raw.githubusercontent.com/microsoft/fluentui-emoji/${FLUENT_REF}/assets/${encodeURIComponent(tile.source)}/Color/${file}`;
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${tile.id}: HTTP ${response.status} for ${url}`);
  const optimized = optimize(await response.text(), svgoConfig).data;
  writeFileSync(new URL(`../public/tiles/${tile.id}.svg`, import.meta.url), optimized);
  total += optimized.length;
  console.log(`${tile.id.padEnd(14)} ${String(optimized.length).padStart(6)} bytes`);
}
console.log(`total ${total} bytes for ${tiles.length} pictures`);

// The kit's win trophy (Fluent "Trophy", Color style) -> public/kit/trophy.svg, used by src/kit/Celebrations.tsx.
mkdirSync(new URL('../public/kit/', import.meta.url), { recursive: true });
const trophyUrl = `https://raw.githubusercontent.com/microsoft/fluentui-emoji/${FLUENT_REF}/assets/Trophy/Color/trophy_color.svg`;
const trophyResponse = await fetch(trophyUrl);
if (!trophyResponse.ok) throw new Error(`trophy: HTTP ${trophyResponse.status} for ${trophyUrl}`);
const trophy = optimize(await trophyResponse.text(), svgoConfig).data;
writeFileSync(new URL('../public/kit/trophy.svg', import.meta.url), trophy);
console.log(`trophy         ${String(trophy.length).padStart(6)} bytes`);

const entries = tiles
  .map((t) => `  { id: '${t.id}', name: { fr: '${t.fr}', en: '${t.en}' } },`)
  .join('\n');
writeFileSync(
  new URL('../src/pictures/tilesFluent.ts', import.meta.url),
  `// GENERATED by scripts/fetch-tiles.mjs from scripts/tiles.json. Do not edit by hand.
// Pictures: Microsoft Fluent Emoji, "Color" style, MIT license (see THIRD_PARTY_NOTICES.md).
import type { PictureCollection } from './types';

export const TILES_FLUENT: PictureCollection = {
  id: 'tiles-fluent',
  basePath: 'tiles',
  pictures: [
${entries}
  ],
};
`,
);
